layout_spectrum: 0.1390391
typography_spectrum: 0.0905503
color:
  saturation: 0.5634056
  lightness: 0.6704611
  brandStrength: 0.1897809
  rhythmicContrast: 0.2026017
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: 'ondrejka '
