color:
  saturation: 0.5634056
  brandStrength: 0.1897809
  rhythmicContrast: 0.2026017
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.6704611
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.1390391
typography_spectrum: 0.0905503
name: 'ondrejka '
