collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5634056
  brandStrength: 0.1897809
  lightness: 0.6704611
  brandColors:
    - '#C5CED5'
    - '#0F140F'
    - '#F9F9F7'
    - '#7290C4'
    - '#565D34'
  rhythmicContrast: 0.2026017
typography_spectrum: 0.0905503
layout_spectrum: 1
name: 'ondrejka '
navigation:
  - name: ih8mud
    url: forum.ih8mud.com
    type: external
